# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: objectdetection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15objectdetection.proto\x12\x0fobjectdetection\".\n\x10InferenceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\",\n\x0eInferenceReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x32\xbe\x01\n\tInference\x12Q\n\tinference\x12!.objectdetection.InferenceRequest\x1a\x1f.objectdetection.InferenceReply\"\x00\x12^\n\x14inferenceStreamReply\x12!.objectdetection.InferenceRequest\x1a\x1f.objectdetection.InferenceReply\"\x00\x30\x01\x42\x06\xa2\x02\x03OBDb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'objectdetection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\003OBD'
  _globals['_INFERENCEREQUEST']._serialized_start=42
  _globals['_INFERENCEREQUEST']._serialized_end=88
  _globals['_INFERENCEREPLY']._serialized_start=90
  _globals['_INFERENCEREPLY']._serialized_end=134
  _globals['_INFERENCE']._serialized_start=137
  _globals['_INFERENCE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
